version: "3.8"

services: 
  web:
    build: .
    restart: always
    environment: 
      - DB_URL=DB_URL=mongodb://db:27017/restaurant
    ports:
      - '3000:3000'

  db:
    image: mongo
    restart: always
    # environment: 
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: example
    # volumes: 
    #   - ./mongo_data:/data/db
    ports:
      - '27017:27017'



    